import fs from 'fs';

const targetJsonPath = 'c:/Users/maddi/Desktop/bts/src/data/btsQuestionBank.json';
const targetJsPath = 'c:/Users/maddi/Desktop/bts/src/data/btsQuestionBank.js';

// Raw Master Lines provided by User
const rawGS = [
  "GS001 | Which song was BTS's debut title track? | A) No More Dream | B) N.O | C) Boy In Luv | D) Danger | ANSWER: A",
  "GS002 | Which song is the title track of O!RUL8,2?? | A) N.O | B) Danger | C) I NEED U | D) Run | ANSWER: A",
  "GS003 | Which song is the title track of SKOOL LUV AFFAIR? | A) Boy In Luv | B) War of Hormone | C) Danger | D) Just One Day | ANSWER: A",
  "GS004 | Which song is the title track of DARK & WILD? | A) Danger | B) RUN | C) DNA | D) Fire | ANSWER: A",
  "GS005 | Which song became the title track of The Most Beautiful Moment in Life Pt.1? | A) I NEED U | B) Run | C) Fire | D) Save ME | ANSWER: A",
  "GS006 | Which song is the title track of The Most Beautiful Moment in Life Pt.2? | A) Run | B) I NEED U | C) Spring Day | D) Blood Sweat & Tears | ANSWER: A",
  "GS007 | Which song was the title track of The Most Beautiful Moment in Life: Young Forever? | A) Fire | B) Save ME | C) Run | D) DNA | ANSWER: A",
  "GS008 | Which BTS song is the title track of WINGS? | A) Blood Sweat & Tears | B) Spring Day | C) Not Today | D) Fake Love | ANSWER: A",
  "GS009 | Which song was added as a title track of You Never Walk Alone? | A) Spring Day | B) DNA | C) IDOL | D) Mic Drop | ANSWER: A",
  "GS010 | Which song was another title track of You Never Walk Alone? | A) Not Today | B) Fake Love | C) Fire | D) Run | ANSWER: A",
  "GS011 | Which song is the title track of LOVE YOURSELF 承 'Her'? | A) DNA | B) Fake Love | C) IDOL | D) Boy With Luv | ANSWER: A",
  "GS012 | Which song is the title track of LOVE YOURSELF 轉 'Tear'? | A) FAKE LOVE | B) DNA | C) IDOL | D) ON | ANSWER: A",
  "GS013 | Which song is the title track of LOVE YOURSELF 結 'Answer'? | A) IDOL | B) DNA | C) FAKE LOVE | D) Spring Day | ANSWER: A",
  "GS014 | Which song is the title track of MAP OF THE SOUL : PERSONA? | A) Boy With Luv | B) ON | C) Black Swan | D) Dionysus | ANSWER: A",
  "GS015 | Which song is the title track of MAP OF THE SOUL : 7? | A) ON | B) Boy With Luv | C) Black Swan | D) Life Goes On | ANSWER: A",
  "GS016 | Which song is the title track of BE? | A) Life Goes On | B) Dynamite | C) Butter | D) Permission to Dance | ANSWER: A",
  "GS017 | Which BTS song became the group's first Billboard Hot 100 No.1? | A) Dynamite | B) Butter | C) DNA | D) Boy With Luv | ANSWER: A",
  "GS018 | Which song is associated with the phrase \"life goes on\" in its title? | A) Life Goes On | B) Spring Day | C) Yet To Come | D) Stay Gold | ANSWER: A",
  "GS019 | Which BTS song has a title referring to a genetic molecule? | A) DNA | B) IDOL | C) ON | D) FIRE | ANSWER: A",
  "GS020 | Which BTS song features the concept of rejecting a false version of oneself in love? | A) Fake Love | B) DNA | C) Butter | D) Dynamite | ANSWER: A",
  "GS021 | Which song is strongly associated with the phrase \"Love yourself\"? | A) Answer: Love Myself | B) Fire | C) Run | D) Dope | ANSWER: A",
  "GS022 | Which BTS song is known for its coffee-related title? | A) Coffee | B) Rain | C) Autumn Leaves | D) Butterfly | ANSWER: A",
  "GS023 | Which BTS song has a title associated with a butterfly? | A) Butterfly | B) Spring Day | C) Save ME | D) Begin | ANSWER: A",
  "GS024 | Which song has a title meaning \"fire\"? | A) Fire | B) Danger | C) Not Today | D) ON | ANSWER: A",
  "GS025 | Which BTS song is famous for the phrase \"MIC Drop\" in its title? | A) MIC Drop | B) Dope | C) Cypher Pt.4 | D) Outro: Tear | ANSWER: A",
  "GS026 | Which song features the title \"Blood Sweat & Tears\"? | A) Blood Sweat & Tears | B) Fake Love | C) Spring Day | D) Lie | ANSWER: A",
  "GS027 | Which BTS song has \"Spring\" in its title? | A) Spring Day | B) Autumn Leaves | C) Winter Bear | D) Rain | ANSWER: A",
  "GS028 | Which song has \"Autumn\" in its title? | A) Autumn Leaves | B) Spring Day | C) Butterfly | D) Rain | ANSWER: A",
  "GS029 | Which BTS song is famous for its \"Dope\" title? | A) Dope | B) Fire | C) Boy In Luv | D) War of Hormone | ANSWER: A",
  "GS030 | Which song features the title \"Save ME\"? | A) Save ME | B) I'm Fine | C) Hold Me Tight | D) Let Me Know | ANSWER: A",
  "GS031 | Which BTS song is the counterpart to \"Save ME\" on LOVE YOURSELF 結 'Answer'? | A) I'm Fine | B) Answer: Love Myself | C) Magic Shop | D) Euphoria | ANSWER: A",
  "GS032 | Which BTS song is associated with a \"Magic Shop\"? | A) Magic Shop | B) House of Cards | C) Paradise | D) Love Maze | ANSWER: A",
  "GS033 | Which BTS song has a title suggesting a \"Paradise\"? | A) Paradise | B) Magic Shop | C) Home | D) Jamais Vu | ANSWER: A",
  "GS034 | Which BTS song has \"Home\" as its title? | A) HOME | B) House of Cards | C) Butterfly | D) Awake | ANSWER: A",
  "GS035 | Which BTS song has \"House of Cards\" as its title? | A) House of Cards | B) Magic Shop | C) Love Maze | D) Rain | ANSWER: A",
  "GS036 | Which BTS song is titled \"Pied Piper\"? | A) Pied Piper | B) Dionysus | C) Anpanman | D) Outro: Tear | ANSWER: A",
  "GS037 | Which song has a title referring to a Japanese sweet bread character? | A) Anpanman | B) Airplane pt.2 | C) Idol | D) Go Go | ANSWER: A",
  "GS038 | Which BTS song is titled \"Go Go\"? | A) Go Go | B) Dope | C) Fire | D) Boy With Luv | ANSWER: A",
  "GS039 | Which BTS song has the title \"Dionysus\"? | A) Dionysus | B) Persona | C) Black Swan | D) ON | ANSWER: A",
  "GS040 | Which song is about continuing despite difficulties and has \"Not Today\" in its title? | A) Not Today | B) ON | C) Run | D) Fire | ANSWER: A",
  "GS041 | Which BTS song has \"Boy With Luv\" in its title? | A) Boy With Luv | B) Boy In Luv | C) Just One Day | D) DNA | ANSWER: A",
  "GS042 | Which song came from BTS's early school-era period and has \"Boy\" in its title? | A) Boy In Luv | B) Boy With Luv | C) DNA | D) HOME | ANSWER: A",
  "GS043 | Which song has the title \"Just One Day\"? | A) Just One Day | B) One Day | C) Tomorrow | D) Rain | ANSWER: A",
  "GS044 | Which BTS song has \"Tomorrow\" as its title? | A) Tomorrow | B) Yet To Come | C) Spring Day | D) Run | ANSWER: A",
  "GS045 | Which BTS song is titled \"Rain\"? | A) Rain | B) Butterfly | C) Autumn Leaves | D) Let Me Know | ANSWER: A",
  "GS046 | Which song has the title \"Let Me Know\"? | A) Let Me Know | B) Hold Me Tight | C) Rain | D) House of Cards | ANSWER: A",
  "GS047 | Which BTS song has the title \"Hold Me Tight\"? | A) Hold Me Tight | B) Save ME | C) Run | D) Butterfly | ANSWER: A",
  "GS048 | Which song has \"I Need U\" as its title? | A) I NEED U | B) I Want U | C) Save ME | D) Let Me Know | ANSWER: A",
  "GS049 | Which BTS song has \"Run\" as its title? | A) Run | B) RUN BTS | C) Run Away | D) Tomorrow | ANSWER: A",
  "GS050 | Which BTS song has \"Danger\" as its title? | A) Danger | B) Fire | C) Dope | D) Attack on Bangtan | ANSWER: A",
  "GS051 | Which BTS song has \"War of Hormone\" as its title? | A) War of Hormone | B) Danger | C) Boy In Luv | D) Boy With Luv | ANSWER: A",
  "GS052 | Which song is titled \"Attack on Bangtan\"? | A) Attack on Bangtan | B) No More Dream | C) N.O | D) Dope | ANSWER: A",
  "GS053 | Which BTS song has \"We Are Bulletproof Pt.2\" in its title? | A) We Are Bulletproof Pt.2 | B) We Are Bulletproof: the Eternal | C) No More Dream | D) Outro: Ego | ANSWER: A",
  "GS054 | Which BTS song has \"N.O\" as its title? | A) N.O | B) No More Dream | C) Danger | D) Tomorrow | ANSWER: A",
  "GS055 | Which BTS song has \"No More Dream\" as its title? | A) No More Dream | B) Dream On | C) Tomorrow | D) N.O | ANSWER: A",
  "GS056 | Which BTS song is titled \"Butterfly\"? | A) Butterfly | B) Spring Day | C) Serendipity | D) Stigma | ANSWER: A",
  "GS057 | Which solo intro belongs to Jung Kook on WINGS? | A) Begin | B) Awake | C) Lie | D) Reflection | ANSWER: A",
  "GS058 | Which solo WINGS track belongs to Jin? | A) Awake | B) Begin | C) Lie | D) Stigma | ANSWER: A",
  "GS059 | Which solo WINGS track belongs to Jimin? | A) Lie | B) Begin | C) Awake | D) First Love | ANSWER: A",
  "GS060 | Which solo WINGS track belongs to V? | A) Stigma | B) Awake | C) Begin | D) Reflection | ANSWER: A",
  "GS061 | Which solo WINGS track belongs to SUGA? | A) First Love | B) MAMA | C) Reflection | D) Awake | ANSWER: A",
  "GS062 | Which solo WINGS track belongs to j-hope? | A) MAMA | B) First Love | C) Begin | D) Stigma | ANSWER: A",
  "GS063 | Which solo WINGS track belongs to RM? | A) Reflection | B) Awake | C) Lie | D) MAMA | ANSWER: A",
  "GS064 | Which BTS song is titled \"Euphoria\"? | A) Euphoria | B) Serendipity | C) Singularity | D) Epiphany | ANSWER: A",
  "GS065 | Which BTS solo track is associated with Jimin in LOVE YOURSELF era? | A) Serendipity | B) Euphoria | C) Singularity | D) Epiphany | ANSWER: A",
  "GS066 | Which BTS solo track is associated with V in LOVE YOURSELF era? | A) Singularity | B) Serendipity | C) Euphoria | D) Epiphany | ANSWER: A",
  "GS067 | Which BTS solo track is associated with Jin in LOVE YOURSELF era? | A) Epiphany | B) Euphoria | C) Singularity | D) Serendipity | ANSWER: A",
  "GS068 | Which BTS song has \"Black Swan\" as its title? | A) Black Swan | B) ON | C) Louder Than Bombs | D) Interlude: Shadow | ANSWER: A",
  "GS069 | Which BTS song has \"Louder than Bombs\" as its title? | A) Louder than Bombs | B) Black Swan | C) Dionysus | D) Jamais Vu | ANSWER: A",
  "GS070 | Which BTS song is titled \"Interlude: Shadow\"? | A) Interlude: Shadow | B) Outro: Ego | C) Intro: Persona | D) Black Swan | ANSWER: A",
  "GS071 | Which BTS song is titled \"Outro: Ego\"? | A) Outro: Ego | B) Interlude: Shadow | C) Intro: Persona | D) ON | ANSWER: A",
  "GS072 | Which BTS song has \"Filter\" as its title? | A) Filter | B) My Time | C) Moon | D) Inner Child | ANSWER: A",
  "GS073 | Which BTS solo track on BE is titled \"Fly to My Room\"? | A) Fly to My Room | B) Blue & Grey | C) Telepathy | D) Dis-ease | ANSWER: A",
  "GS074 | Which BTS song has \"Blue & Grey\" in its title? | A) Blue & Grey | B) Life Goes On | C) Stay | D) Telepathy | ANSWER: A",
  "GS075 | Which BTS song has \"Telepathy\" as its title? | A) Telepathy | B) Dis-ease | C) Fly to My Room | D) Stay | ANSWER: A",
  "GS076 | Which BTS song has \"Dis-ease\" as its title? | A) Dis-ease | B) Blue & Grey | C) Telepathy | D) Life Goes On | ANSWER: A",
  "GS077 | Which BTS song has \"Stay\" as its title on BE? | A) Stay | B) Home | C) Answer: Love Myself | D) Spring Day | ANSWER: A",
  "GS078 | Which song is the title track of BTS's anthology album Proof? | A) Yet To Come | B) Run BTS | C) For Youth | D) Born Singer | ANSWER: A",
  "GS079 | Which BTS song is titled \"Run BTS\"? | A) Run BTS | B) Run | C) RUN BTS! | D) Not Today | ANSWER: A",
  "GS080 | Which BTS song is titled \"For Youth\"? | A) For Youth | B) Young Forever | C) Youth | D) Yet To Come | ANSWER: A",
  "GS081 | Which song is BTS's fan song associated with 2022's Proof? | A) For Youth | B) Spring Day | C) Magic Shop | D) Mikrokosmos | ANSWER: A",
  "GS082 | Which BTS song is titled \"Mikrokosmos\"? | A) Mikrokosmos | B) 134340 | C) Moon | D) Galaxy | ANSWER: A",
  "GS083 | Which BTS song has the title \"134340\"? | A) 134340 | B) Mikrokosmos | C) Moon | D) Pluto | ANSWER: A",
  "GS084 | Which BTS song is titled \"Moon\"? | A) Moon | B) Mikrokosmos | C) Stigma | D) Serendipity | ANSWER: A",
  "GS085 | Which BTS song has \"Paradise\" as its title? | A) Paradise | B) Home | C) Magic Shop | D) Love Maze | ANSWER: A",
  "GS086 | Which BTS song has \"Love Maze\" as its title? | A) Love Maze | B) Paradise | C) Magic Shop | D) Pied Piper | ANSWER: A",
  "GS087 | Which BTS song has \"Anpanman\" as its title? | A) Anpanman | B) Go Go | C) Airplane pt.2 | D) Dionysus | ANSWER: A",
  "GS088 | Which BTS song has \"Airplane pt.2\" as its title? | A) Airplane pt.2 | B) Airplane | C) Anpanman | D) Outro: Tear | ANSWER: A",
  "GS089 | Which BTS song has \"Jamais Vu\" as its title? | A) Jamais Vu | B) Black Swan | C) HOME | D) Make It Right | ANSWER: A",
  "GS090 | Which BTS song has \"Make It Right\" as its title? | A) Make It Right | B) Boy With Luv | C) HOME | D) Mikrokosmos | ANSWER: A",
  "GS091 | Which BTS song has \"I'm Fine\" as its title? | A) I'm Fine | B) Save ME | C) Answer: Love Myself | D) Magic Shop | ANSWER: A",
  "GS092 | Which BTS song is titled \"The Truth Untold\"? | A) The Truth Untold | B) Fake Love | C) House of Cards | D) Outro: Tear | ANSWER: A",
  "GS093 | Which BTS song is titled \"Outro: Tear\"? | A) Outro: Tear | B) The Truth Untold | C) Interlude: Shadow | D) Outro: Ego | ANSWER: A",
  "GS094 | Which BTS song is titled \"Pied Piper\"? | A) Pied Piper | B) Magic Shop | C) Anpanman | D) Paradise | ANSWER: A",
  "GS095 | Which BTS song is titled \"2! 3!\"? | A) 2! 3! | B) 1! 2! 3! | C) 2 Cool 4 Skool | D) 3! 2! | ANSWER: A",
  "GS096 | Which BTS song has \"We Are Bulletproof: the Eternal\" as its title? | A) We Are Bulletproof: the Eternal | B) We Are Bulletproof Pt.2 | C) Answer: Love Myself | D) Young Forever | ANSWER: A",
  "GS097 | Which BTS song is titled \"Butter\"? | A) Butter | B) Dynamite | C) Permission to Dance | D) Life Goes On | ANSWER: A",
  "GS098 | Which BTS song is titled \"Permission to Dance\"? | A) Permission to Dance | B) Butter | C) Dynamite | D) Boy With Luv | ANSWER: A",
  "GS099 | Which BTS song is titled \"Yet To Come\"? | A) Yet To Come | B) For Youth | C) Life Goes On | D) Spring Day | ANSWER: A",
  "GS100 | Which BTS song is titled \"Take Two\"? | A) Take Two | B) Yet To Come | C) For Youth | D) Spring Day | ANSWER: A"
];

const rawGM = [
  "GM001 | Who is BTS's leader? | A) Jin | B) RM | C) Jimin | D) V | ANSWER: B",
  "GM002 | Who is BTS's oldest member? | A) Jin | B) SUGA | C) RM | D) j-hope | ANSWER: A",
  "GM003 | Who is BTS's youngest member? | A) Jimin | B) V | C) Jung Kook | D) Jin | ANSWER: C",
  "GM004 | Which member is known by the stage name RM? | A) Kim Namjoon | B) Kim Seokjin | C) Min Yoongi | D) Jung Hoseok | ANSWER: A",
  "GM005 | Which member is known as Kim Seokjin? | A) Jin | B) V | C) RM | D) Jung Kook | ANSWER: A",
  "GM006 | Which member's birth name is Min Yoongi? | A) SUGA | B) RM | C) j-hope | D) Jin | ANSWER: A",
  "GM007 | Which member's birth name is Jung Hoseok? | A) j-hope | B) Jimin | C) V | D) SUGA | ANSWER: A",
  "GM008 | Which member's birth name is Park Jimin? | A) Jimin | B) Jin | C) V | D) Jung Kook | ANSWER: A",
  "GM009 | Which member's birth name is Kim Taehyung? | A) V | B) Jin | C) RM | D) SUGA | ANSWER: A",
  "GM010 | Which member's birth name is Jeon Jung Kook? | A) Jung Kook | B) Jimin | C) V | D) j-hope | ANSWER: A",
  "GM011 | Which member is the leader and rapper? | A) RM | B) Jin | C) Jimin | D) V | ANSWER: A",
  "GM012 | Which member is known for the solo song Awake? | A) Jin | B) Jimin | C) SUGA | D) V | ANSWER: A",
  "GM013 | Which member is associated with Begin from WINGS? | A) Jung Kook | B) Jin | C) V | D) RM | ANSWER: A",
  "GM014 | Which member is associated with First Love from WINGS? | A) SUGA | B) j-hope | C) Jimin | D) Jin | ANSWER: A",
  "GM015 | Which member is associated with MAMA from WINGS? | A) j-hope | B) RM | C) Jin | D) Jung Kook | ANSWER: A",
  "GM016 | Which member is associated with Reflection from WINGS? | A) RM | B) SUGA | C) V | D) Jimin | ANSWER: A",
  "GM017 | Which member is associated with Lie from WINGS? | A) Jimin | B) Jung Kook | C) Jin | D) j-hope | ANSWER: A",
  "GM018 | Which member is associated with Stigma from WINGS? | A) V | B) Jimin | C) RM | D) SUGA | ANSWER: A",
  "GM019 | Which member is associated with Epiphany? | A) Jin | B) V | C) Jung Kook | D) RM | ANSWER: A",
  "GM020 | Which member is associated with Serendipity? | A) Jimin | B) V | C) Jin | D) SUGA | ANSWER: A",
  "GM021 | Which member is associated with Singularity? | A) V | B) Jimin | C) Jung Kook | D) RM | ANSWER: A",
  "GM022 | Which member is associated with Euphoria? | A) Jung Kook | B) Jin | C) Jimin | D) V | ANSWER: A",
  "GM023 | Which member is associated with Intro: Persona? | A) RM | B) SUGA | C) j-hope | D) Jin | ANSWER: A",
  "GM024 | Which member is associated with Interlude: Shadow? | A) SUGA | B) RM | C) V | D) Jung Kook | ANSWER: A",
  "GM025 | Which member is associated with Outro: Ego? | A) j-hope | B) RM | C) Jin | D) Jimin | ANSWER: A",
  "GM026 | Which member is known for the solo track Filter? | A) Jimin | B) V | C) Jung Kook | D) Jin | ANSWER: A",
  "GM027 | Which member is associated with My Time? | A) Jung Kook | B) Jimin | C) RM | D) V | ANSWER: A",
  "GM028 | Which member is associated with Inner Child? | A) V | B) Jin | C) Jimin | D) j-hope | ANSWER: A",
  "GM029 | Which member is associated with Moon? | A) Jin | B) V | C) Jung Kook | D) SUGA | ANSWER: A",
  "GM030 | Which member is associated with Black Swan performance video? | A) BTS as a group | B) Jin only | C) RM only | D) V only | ANSWER: A",
  "GM031 | Which member is famous for the stage name j-hope? | A) Jung Hoseok | B) Kim Namjoon | C) Min Yoongi | D) Park Jimin | ANSWER: A",
  "GM032 | Which member is famous for the stage name SUGA? | A) Min Yoongi | B) Kim Taehyung | C) Kim Seokjin | D) Jeon Jung Kook | ANSWER: A",
  "GM033 | Which member is famous for the stage name V? | A) Kim Taehyung | B) Kim Namjoon | C) Jung Hoseok | D) Park Jimin | ANSWER: A",
  "GM034 | Which member is famous for the stage name Jin? | A) Kim Seokjin | B) Min Yoongi | C) Kim Taehyung | D) Jung Hoseok | ANSWER: A",
  "GM035 | Which member is famous for the stage name Jimin? | A) Park Jimin | B) Kim Namjoon | C) Jeon Jung Kook | D) Kim Seokjin | ANSWER: A",
  "GM036 | Which member is famous for the stage name Jung Kook? | A) Jeon Jung Kook | B) Kim Taehyung | C) Min Yoongi | D) Park Jimin | ANSWER: A",
  "GM037 | Which member is famous for the stage name RM? | A) Kim Namjoon | B) Kim Seokjin | C) Jung Hoseok | D) Min Yoongi | ANSWER: A",
  "GM038 | Which member is the group's youngest? | A) Jung Kook | B) Jimin | C) V | D) Jin | ANSWER: A",
  "GM039 | Which member is the group's oldest? | A) Jin | B) RM | C) SUGA | D) j-hope | ANSWER: A",
  "GM040 | Which member is BTS's leader? | A) RM | B) Jin | C) V | D) Jimin | ANSWER: A",
  "GM041 | Which member is strongly associated with dance and performance leadership? | A) j-hope | B) RM | C) Jin | D) SUGA | ANSWER: A",
  "GM042 | Which member is known for his deep, distinctive singing voice? | A) V | B) Jimin | C) Jung Kook | D) Jin | ANSWER: A",
  "GM043 | Which member is known for a high, distinctive vocal tone? | A) Jimin | B) V | C) RM | D) SUGA | ANSWER: A",
  "GM044 | Which member is part of BTS's rap line? | A) SUGA | B) Jin | C) Jimin | D) V | ANSWER: A",
  "GM045 | Which member is part of BTS's rap line? | A) j-hope | B) Jin | C) Jimin | D) V | ANSWER: A",
  "GM046 | Which member is part of BTS's rap line? | A) RM | B) Jin | C) Jimin | D) V | ANSWER: A",
  "GM047 | Which member is part of BTS's vocal line? | A) Jin | B) RM | C) SUGA | D) j-hope | ANSWER: A",
  "GM048 | Which member is part of BTS's vocal line? | A) Jimin | B) RM | C) SUGA | D) j-hope | ANSWER: A",
  "GM049 | Which member is part of BTS's vocal line? | A) V | B) RM | C) SUGA | D) j-hope | ANSWER: A",
  "GM050 | Which member is part of BTS's vocal line? | A) Jung Kook | B) RM | C) SUGA | D) j-hope | ANSWER: A",
  "GM051 | Which member released the solo album FACE? | A) Jimin | B) V | C) Jin | D) RM | ANSWER: A",
  "GM052 | Which member released the solo album GOLDEN? | A) Jung Kook | B) Jimin | C) V | D) Jin | ANSWER: A",
  "GM053 | Which member released the solo album Layover? | A) V | B) Jimin | C) Jung Kook | D) RM | ANSWER: A",
  "GM054 | Which member released the solo album Indigo? | A) RM | B) SUGA | C) Jin | D) j-hope | ANSWER: A",
  "GM055 | Which member released the solo album D-DAY? | A) SUGA | B) RM | C) j-hope | D) Jin | ANSWER: A",
  "GM056 | Which member released the solo album Jack In The Box? | A) j-hope | B) SUGA | C) RM | D) Jin | ANSWER: A",
  "GM057 | Which member released The Astronaut? | A) Jin | B) V | C) Jimin | D) Jung Kook | ANSWER: A",
  "GM058 | Which member released Like Crazy? | A) Jimin | B) Jung Kook | C) V | D) RM | ANSWER: A",
  "GM059 | Which member released Seven as a solo single? | A) Jung Kook | B) Jimin | C) V | D) Jin | ANSWER: A",
  "GM060 | Which member released Slow Dancing? | A) V | B) Jimin | C) Jung Kook | D) RM | ANSWER: A",
  "GM061 | Which member released Arson? | A) j-hope | B) SUGA | C) RM | D) Jin | ANSWER: A",
  "GM062 | Which member released People Pt.2 with IU? | A) SUGA | B) RM | C) V | D) Jimin | ANSWER: A",
  "GM063 | Which member released Wild Flower? | A) RM | B) Jin | C) Jung Kook | D) j-hope | ANSWER: A",
  "GM064 | Which member released Moon as a solo BTS track? | A) Jin | B) V | C) Jimin | D) Jung Kook | ANSWER: A",
  "GM065 | Which member is known for the song Stigma? | A) V | B) Jin | C) Jimin | D) RM | ANSWER: A",
  "GM066 | Which member is known for the song Lie? | A) Jimin | B) V | C) Jung Kook | D) Jin | ANSWER: A",
  "GM067 | Which member is known for the song First Love? | A) SUGA | B) j-hope | C) RM | D) Jin | ANSWER: A",
  "GM068 | Which member is known for the song MAMA? | A) j-hope | B) RM | C) SUGA | D) V | ANSWER: A",
  "GM069 | Which member is known for the song Reflection? | A) RM | B) SUGA | C) j-hope | D) Jin | ANSWER: A",
  "GM070 | Which member is known for the song Begin? | A) Jung Kook | B) Jimin | C) V | D) Jin | ANSWER: A",
  "GM071 | Which member is known for the song Awake? | A) Jin | B) Jung Kook | C) Jimin | D) V | ANSWER: A",
  "GM072 | Which member is known for the song Persona? | A) RM | B) SUGA | C) j-hope | D) Jin | ANSWER: A",
  "GM073 | Which member is known for the song Shadow? | A) SUGA | B) RM | C) V | D) Jimin | ANSWER: A",
  "GM074 | Which member is known for the song Ego? | A) j-hope | B) Jin | C) Jung Kook | D) RM | ANSWER: A",
  "GM075 | Which member is associated with the solo track Serendipity? | A) Jimin | B) V | C) Jin | D) Jung Kook | ANSWER: A",
  "GM076 | Which member is associated with the solo track Singularity? | A) V | B) Jimin | C) Jung Kook | D) Jin | ANSWER: A",
  "GM077 | Which member is associated with the solo track Euphoria? | A) Jung Kook | B) Jin | C) V | D) Jimin | ANSWER: A",
  "GM078 | Which member is associated with Epiphany? | A) Jin | B) V | C) Jimin | D) Jung Kook | ANSWER: A",
  "GM079 | Which member is known as BTS's sunshine-like performer and dancer? | A) j-hope | B) RM | C) Jin | D) SUGA | ANSWER: A",
  "GM080 | Which member is known for the nickname Worldwide Handsome? | A) Jin | B) V | C) RM | D) Jung Kook | ANSWER: A",
  "GM081 | Which member is known for producing and songwriting as Agust D? | A) SUGA | B) RM | C) j-hope | D) Jin | ANSWER: A",
  "GM082 | Which member is known for the artistic persona Agust D? | A) SUGA | B) V | C) Jimin | D) Jung Kook | ANSWER: A",
  "GM083 | Which member has the stage name meaning \"Hope\"? | A) j-hope | B) RM | C) Jin | D) SUGA | ANSWER: A",
  "GM084 | Which member is the youngest of the seven? | A) Jung Kook | B) V | C) Jimin | D) Jin | ANSWER: A",
  "GM085 | Which member is the oldest of the seven? | A) Jin | B) RM | C) SUGA | D) j-hope | ANSWER: A",
  "GM086 | Which member is known as Kim Namjoon? | A) RM | B) Jin | C) V | D) SUGA | ANSWER: A",
  "GM087 | Which member is known as Min Yoongi? | A) SUGA | B) RM | C) Jin | D) j-hope | ANSWER: A",
  "GM088 | Which member is known as Jung Hoseok? | A) j-hope | B) RM | C) Jimin | D) V | ANSWER: A",
  "GM089 | Which member is known as Park Jimin? | A) Jimin | B) Jin | C) Jung Kook | D) V | ANSWER: A",
  "GM090 | Which member is known as Kim Taehyung? | A) V | B) Jin | C) RM | D) Jung Kook | ANSWER: A",
  "GM091 | Which member is known as Jeon Jung Kook? | A) Jung Kook | B) Jimin | C) V | D) Jin | ANSWER: A",
  "GM092 | Which member is known as Kim Seokjin? | A) Jin | B) RM | C) SUGA | D) j-hope | ANSWER: A",
  "GM093 | Which member is associated with the album Indigo? | A) RM | B) SUGA | C) j-hope | D) V | ANSWER: A",
  "GM094 | Which member is associated with the album Jack In The Box? | A) j-hope | B) RM | C) SUGA | D) Jin | ANSWER: A",
  "GM095 | Which member is associated with the album D-DAY? | A) SUGA | B) RM | C) V | D) Jung Kook | ANSWER: A",
  "GM096 | Which member is associated with the album FACE? | A) Jimin | B) V | C) Jung Kook | D) Jin | ANSWER: A",
  "GM097 | Which member is associated with the album Layover? | A) V | B) Jimin | C) Jin | D) Jung Kook | ANSWER: A",
  "GM098 | Which member is associated with the album GOLDEN? | A) Jung Kook | B) Jimin | C) V | D) RM | ANSWER: A",
  "GM099 | Which member is associated with the album Happy? | A) Jin | B) V | C) RM | D) SUGA | ANSWER: A",
  "GM100 | Which member is associated with the album MUSE? | A) Jimin | B) Jung Kook | C) V | D) Jin | ANSWER: A"
];

const rawEM = [
  "EM001 | 🧬💜🎶 | Which song? | A) DNA | B) Fire | C) Spring Day | D) IDOL | ANSWER: A",
  "EM002 | 🌸🌧️💜 | Which song? | A) Spring Day | B) Butter | C) DNA | D) MIC Drop | ANSWER: A",
  "EM003 | 🔥🔥🎤 | Which song? | A) Fire | B) Fake Love | C) Run | D) HOME | ANSWER: A",
  "EM004 | 🎤💔🎭 | Which song? | A) Fake Love | B) DNA | C) Butter | D) Dynamite | ANSWER: A",
  "EM005 | 💧🩸😢 | Which song? | A) Blood Sweat & Tears | B) Fire | C) IDOL | D) ON | ANSWER: A",
  "EM006 | 🎙️⬇️💿 | Which song? | A) MIC Drop | B) DNA | C) Run | D) HOME | ANSWER: A",
  "EM007 | 🚫📅🔥 | Which song? | A) Not Today | B) Tomorrow | C) Run | D) Fire | ANSWER: A",
  "EM008 | 🏃‍♂️💨💜 | Which song? | A) Run | B) Spring Day | C) DNA | D) N.O | ANSWER: A",
  "EM009 | 🦋💜🎵 | Which song? | A) Butterfly | B) Spring Day | C) Euphoria | D) Save ME | ANSWER: A",
  "EM010 | 🆘🙋💜 | Which song? | A) Save ME | B) I'm Fine | C) HOME | D) Run | ANSWER: A",
  "EM011 | 🧑🎤❤️👦 | Which song? | A) Boy With Luv | B) Boy In Luv | C) DNA | D) IDOL | ANSWER: A",
  "EM012 | 🧑🎓❤️🎤 | Which song? | A) Boy In Luv | B) Boy With Luv | C) Run | D) HOME | ANSWER: A",
  "EM013 | 🎭👑💜 | Which song? | A) IDOL | B) DNA | C) Fake Love | D) Fire | ANSWER: A",
  "EM014 | 🧠🗺️🎤 | Which era? | A) MAP OF THE SOUL | B) WINGS | C) LOVE YOURSELF | D) School Trilogy | ANSWER: A",
  "EM015 | 💜❤️🪞 | Which era? | A) LOVE YOURSELF | B) WINGS | C) BE | D) Dark & Wild | ANSWER: A",
  "EM016 | 🪽🔥🖤 | Which era? | A) WINGS | B) LOVE YOURSELF | C) MAP OF THE SOUL | D) School Trilogy | ANSWER: A",
  "EM017 | 🏫🎒🎤 | Which era? | A) School Trilogy | B) WINGS | C) BE | D) Proof | ANSWER: A",
  "EM018 | 🧑🎤🎓💜 | Which era? | A) School Trilogy | B) LOVE YOURSELF | C) MAP OF THE SOUL | D) WINGS | ANSWER: A",
  "EM019 | 💿🧬💜 | Which song? | A) DNA | B) Butter | C) Fire | D) IDOL | ANSWER: A",
  "EM020 | 🕺🪩☀️ | Which song? | A) Dynamite | B) Butter | C) DNA | D) Spring Day | ANSWER: A",
  "EM021 | 🧈🎤🕺 | Which song? | A) Butter | B) Dynamite | C) Permission to Dance | D) IDOL | ANSWER: A",
  "EM022 | 💃🕺🎶👐 | Which song? | A) Permission to Dance | B) Butter | C) Dynamite | D) DNA | ANSWER: A",
  "EM023 | 🕰️💜🎤 | Which song? | A) Yet To Come | B) Spring Day | C) Run | D) Take Two | ANSWER: A",
  "EM024 | 👨👦👦7️⃣💜 | What does this most directly represent? | A) BTS's seven members | B) BTS's first album | C) ARIRANG | D) WINGS | ANSWER: A",
  "EM025 | 💜👥🌎 | What does this most directly represent? | A) ARMY | B) WINGS | C) DNA | D) BE | ANSWER: A",
  "EM026 | 🎤7️⃣🌟 | What does this represent? | A) BTS | B) ARMY | C) Dynamite | D) Proof | ANSWER: A",
  "EM027 | 🏠💜🎶 | Which song? | A) HOME | B) Magic Shop | C) Paradise | D) Love Maze | ANSWER: A",
  "EM028 | ✨🏪💜 | Which song? | A) Magic Shop | B) HOME | C) Paradise | D) Pied Piper | ANSWER: A",
  "EM029 | 🏝️🌴😌 | Which song? | A) Paradise | B) HOME | C) Magic Shop | D) Airplane pt.2 | ANSWER: A",
  "EM030 | 🌀❤️🧩 | Which song? | A) Love Maze | B) Magic Shop | C) Paradise | D) Pied Piper | ANSWER: A",
  "EM031 | 🎵🐍🎹 | Which song? | A) Pied Piper | B) Dionysus | C) Anpanman | D) Go Go | ANSWER: A",
  "EM032 | 🍞🦸‍♂️💜 | Which song? | A) Anpanman | B) Go Go | C) Fire | D) IDOL | ANSWER: A",
  "EM033 | 💰🕺💸 | Which song? | A) Go Go | B) Dope | C) Fire | D) MIC Drop | ANSWER: A",
  "EM034 | 🍷🏛️🎭 | Which song? | A) Dionysus | B) Black Swan | C) ON | D) Persona | ANSWER: A",
  "EM035 | 🖤🦢🎭 | Which song? | A) Black Swan | B) ON | C) Dionysus | D) Fake Love | ANSWER: A",
  "EM036 | 💣🔊🌑 | Which song? | A) Louder than Bombs | B) Black Swan | C) ON | D) MIC Drop | ANSWER: A",
  "EM037 | 🌌🔭💜 | Which song? | A) Mikrokosmos | B) 134340 | C) Moon | D) DNA | ANSWER: A",
  "EM038 | 🪐❄️💜 | Which song? | A) 134340 | B) Mikrokosmos | C) Moon | D) Euphoria | ANSWER: A",
  "EM039 | 🌙🎤💜 | Which song? | A) Moon | B) Mikrokosmos | C) Euphoria | D) Serendipity | ANSWER: A",
  "EM040 | 🌈😊💜 | Which song? | A) Euphoria | B) Serendipity | C) Epiphany | D) Singularity | ANSWER: A",
  "EM041 | 🍀💜✨ | Which song? | A) Serendipity | B) Euphoria | C) Epiphany | D) Moon | ANSWER: A",
  "EM042 | 🎭🖤🎙️ | Which song? | A) Singularity | B) Serendipity | C) Euphoria | D) Epiphany | ANSWER: A",
  "EM043 | 🪞💡❤️ | Which song? | A) Epiphany | B) Singularity | C) Euphoria | D) Moon | ANSWER: A",
  "EM044 | 🧑🎤🧬❤️ | Which member? | A) RM | B) Jin | C) V | D) SUGA | ANSWER: A",
  "EM045 | 👑🤴🎤 | Which member? | A) Jin | B) RM | C) Jimin | D) j-hope | ANSWER: A",
  "EM046 | 🎧🎹🔥 | Which member? | A) SUGA | B) V | C) Jin | D) Jung Kook | ANSWER: A",
  "EM047 | ☀️🕺💃 | Which member? | A) j-hope | B) RM | C) Jin | D) SUGA | ANSWER: A",
  "EM048 | 🩰🎤✨ | Which member? | A) Jimin | B) V | C) Jin | D) RM | ANSWER: A",
  "EM049 | 🎨📷🎤 | Which member? | A) V | B) Jimin | C) Jung Kook | D) RM | ANSWER: A",
  "EM050 | 🐰🎤🎧 | Which member? | A) Jung Kook | B) V | C) Jimin | D) Jin | ANSWER: A",
  "EM051 | 🧠🎤👑 | Which member? | A) RM | B) SUGA | C) Jin | D) V | ANSWER: A",
  "EM052 | 🍜😎🎤 | Which member? | A) Jin | B) j-hope | C) Jimin | D) RM | ANSWER: A",
  "EM053 | 🎹🎧✍️ | Which member? | A) SUGA | B) Jin | C) V | D) Jung Kook | ANSWER: A",
  "EM054 | 🌞🕺❤️ | Which member? | A) j-hope | B) Jimin | C) V | D) Jin | ANSWER: A",
  "EM055 | 🩰🦋🎤 | Which member? | A) Jimin | B) Jung Kook | C) Jin | D) RM | ANSWER: A",
  "EM056 | 🐻🎨🎤 | Which member? | A) V | B) Jung Kook | C) Jimin | D) SUGA | ANSWER: A",
  "EM057 | 🐰🌟🎤 | Which member? | A) Jung Kook | B) V | C) Jin | D) RM | ANSWER: A",
  "EM058 | 🏫🎒7️⃣ | Which era? | A) School Trilogy | B) WINGS | C) LOVE YOURSELF | D) BE | ANSWER: A",
  "EM059 | 🌹🪞❤️ | Which era? | A) LOVE YOURSELF | B) WINGS | C) School Trilogy | D) Proof | ANSWER: A",
  "EM060 | 🪽🌑🔥 | Which era? | A) WINGS | B) LOVE YOURSELF | C) BE | D) MAP OF THE SOUL | ANSWER: A",
  "EM061 | 🧠🎭🗺️ | Which era? | A) MAP OF THE SOUL | B) LOVE YOURSELF | C) WINGS | D) Proof | ANSWER: A",
  "EM062 | 🏠🦠🌍 | Which era? | A) BE | B) WINGS | C) School Trilogy | D) Dark & Wild | ANSWER: A",
  "EM063 | 📚🕰️💿 | Which era/release? | A) Proof | B) BE | C) WINGS | D) LOVE YOURSELF | ANSWER: A",
  "EM064 | 🏫❤️🎤 | Which song? | A) Boy In Luv | B) Boy With Luv | C) DNA | D) Run | ANSWER: A",
  "EM065 | 🧑🎤💞🌸 | Which song? | A) Boy With Luv | B) Boy In Luv | C) Spring Day | D) HOME | ANSWER: A",
  "EM066 | 🌧️🫂💜 | Which song? | A) Spring Day | B) Save ME | C) Run | D) I'm Fine | ANSWER: A",
  "EM067 | 🆘❤️🙏 | Which song? | A) Save ME | B) I'm Fine | C) Fire | D) Not Today | ANSWER: A",
  "EM068 | 😊🌈👐 | Which song? | A) Permission to Dance | B) Butter | C) Dynamite | D) Boy With Luv | ANSWER: A",
  "EM069 | 🧈💃🕺 | Which song? | A) Butter | B) Dynamite | C) Permission to Dance | D) DNA | ANSWER: A",
  "EM070 | 💥🪩🌟 | Which song? | A) Dynamite | B) Butter | C) Fire | D) IDOL | ANSWER: A",
  "EM071 | 🫶🌌🎶 | Which song? | A) Mikrokosmos | B) Moon | C) DNA | D) Spring Day | ANSWER: A",
  "EM072 | 🦋🌙💜 | Which song? | A) Butterfly | B) Moon | C) Serendipity | D) Spring Day | ANSWER: A",
  "EM073 | 🩸💧💃 | Which song? | A) Blood Sweat & Tears | B) Fake Love | C) Fire | D) Black Swan | ANSWER: A",
  "EM074 | 🖤🦢🎼 | Which song? | A) Black Swan | B) Blood Sweat & Tears | C) Fake Love | D) ON | ANSWER: A",
  "EM075 | 🎭❤️🩹🪞 | Which song? | A) Fake Love | B) IDOL | C) DNA | D) Butter | ANSWER: A",
  "EM076 | 👑🎭💜 | Which song? | A) IDOL | B) Fake Love | C) DNA | D) ON | ANSWER: A",
  "EM077 | 🏃‍♂️🌅💜 | Which song? | A) Run | B) Spring Day | C) I NEED U | D) Not Today | ANSWER: A",
  "EM078 | 😭❤️🆘 | Which song? | A) I NEED U | B) Save ME | C) Run | D) Butterfly | ANSWER: A",
  "EM079 | 🔥🚫🙅 | Which song? | A) Not Today | B) Fire | C) ON | D) Dope | ANSWER: A",
  "EM080 | 🎤💥💧 | Which song? | A) MIC Drop | B) Fire | C) Dope | D) Dionysus | ANSWER: A",
  "EM081 | 💪🧑🎤⚡ | Which song? | A) Dope | B) Fire | C) MIC Drop | D) Not Today | ANSWER: A",
  "EM082 | 🌱🌸⏳ | Which song? | A) Spring Day | B) Yet To Come | C) Young Forever | D) Run | ANSWER: A",
  "EM083 | 🕰️🌟🔜 | Which song? | A) Yet To Come | B) Spring Day | C) Take Two | D) For Youth | ANSWER: A",
  "EM084 | 2️⃣👨👩👦👦💜 | Which song? | A) Take Two | B) 2! 3! | C) For Youth | D) Young Forever | ANSWER: A",
  "EM085 | 🎈🎤💜 | Which song? | A) For Youth | B) Take Two | C) Yet To Come | D) Spring Day | ANSWER: A",
  "EM086 | 🫂🏠💜 | Which song? | A) HOME | B) Magic Shop | C) Paradise | D) Love Maze | ANSWER: A",
  "EM087 | 🪄🚪💜 | Which song? | A) Magic Shop | B) HOME | C) Paradise | D) Pied Piper | ANSWER: A",
  "EM088 | 🏝️🌴😎 | Which song? | A) Paradise | B) HOME | C) Love Maze | D) Magic Shop | ANSWER: A",
  "EM089 | 🐍🎶🎤 | Which song? | A) Pied Piper | B) Magic Shop | C) Anpanman | D) Go Go | ANSWER: A",
  "EM090 | 🍞🦸 | Which song? | A) Anpanman | B) Pied Piper | C) Go Go | D) IDOL | ANSWER: A",
  "EM091 | 💸🕺💰 | Which song? | A) Go Go | B) Dope | C) Fire | D) MIC Drop | ANSWER: A",
  "EM092 | 🍷🏛️🎤 | Which song? | A) Dionysus | B) Black Swan | C) ON | D) IDOL | ANSWER: A",
  "EM093 | 🧬💿7️⃣ | Which era? | A) MAP OF THE SOUL : 7 | B) LOVE YOURSELF | C) WINGS | D) BE | ANSWER: A",
  "EM094 | 🧑🎤🎭🪞 | Which era? | A) MAP OF THE SOUL : PERSONA | B) WINGS | C) BE | D) Proof | ANSWER: A",
  "EM095 | 🏠🦠🎧 | Which album? | A) BE | B) Proof | C) WINGS | D) DARK & WILD | ANSWER: A",
  "EM096 | 📖🧾🎶 | Which album? | A) Proof | B) BE | C) WINGS | D) LOVE YOURSELF 結 'Answer' | ANSWER: A",
  "EM097 | 🪩💜🌟 | Which song? | A) Dynamite | B) Butter | C) IDOL | D) DNA | ANSWER: A",
  "EM098 | 🧈✨🎤 | Which song? | A) Butter | B) Dynamite | C) Permission to Dance | D) DNA | ANSWER: A",
  "EM099 | 👐💃🕺🌍 | Which song? | A) Permission to Dance | B) Butter | C) Dynamite | D) Boy With Luv | ANSWER: A",
  "EM100 | 7️⃣💜🌍🎤 | Who/what does this represent? | A) BTS | B) ARMY | C) WINGS | D) Proof | ANSWER: A"
];

const rawGE = [
  "GE001 | Which era is associated with No More Dream? | A) School Trilogy | B) WINGS | C) LOVE YOURSELF | D) BE | ANSWER: A",
  "GE002 | Which era is associated with N.O? | A) School Trilogy | B) LOVE YOURSELF | C) WINGS | D) MAP OF THE SOUL | ANSWER: A",
  "GE003 | Which era is associated with Boy In Luv? | A) School Trilogy | B) WINGS | C) BE | D) Proof | ANSWER: A",
  "GE004 | Which era is associated with Just One Day? | A) School Trilogy | B) LOVE YOURSELF | C) MAP OF THE SOUL | D) BE | ANSWER: A",
  "GE005 | Which era contains Dark & Wild? | A) DARK & WILD | B) WINGS | C) BE | D) Proof | ANSWER: A",
  "GE006 | Which era introduced I NEED U? | A) The Most Beautiful Moment in Life | B) LOVE YOURSELF | C) WINGS | D) MAP OF THE SOUL | ANSWER: A",
  "GE007 | Which era introduced Run? | A) The Most Beautiful Moment in Life | B) DARK & WILD | C) WINGS | D) BE | ANSWER: A",
  "GE008 | Which era contains Fire? | A) The Most Beautiful Moment in Life: Young Forever | B) LOVE YOURSELF | C) WINGS | D) BE | ANSWER: A",
  "GE009 | Which era is associated with Save ME? | A) The Most Beautiful Moment in Life: Young Forever | B) WINGS | C) MAP OF THE SOUL | D) Proof | ANSWER: A",
  "GE010 | Which era contains Blood Sweat & Tears? | A) WINGS | B) LOVE YOURSELF | C) BE | D) School Trilogy | ANSWER: A",
  "GE011 | Which era contains Spring Day? | A) You Never Walk Alone | B) WINGS | C) LOVE YOURSELF | D) BE | ANSWER: A",
  "GE012 | Which era contains Not Today? | A) You Never Walk Alone | B) MAP OF THE SOUL | C) LOVE YOURSELF | D) DARK & WILD | ANSWER: A",
  "GE013 | Which era contains DNA? | A) LOVE YOURSELF | B) WINGS | C) BE | D) School Trilogy | ANSWER: A",
  "GE014 | Which era contains Fake Love? | A) LOVE YOURSELF | B) MAP OF THE SOUL | C) WINGS | D) BE | ANSWER: A",
  "GE015 | Which era contains IDOL? | A) LOVE YOURSELF | B) School Trilogy | C) WINGS | D) BE | ANSWER: A",
  "GE016 | Which era contains Boy With Luv? | A) MAP OF THE SOUL | B) LOVE YOURSELF | C) WINGS | D) BE | ANSWER: A",
  "GE017 | Which era contains Black Swan? | A) MAP OF THE SOUL | B) LOVE YOURSELF | C) WINGS | D) BE | ANSWER: A",
  "GE018 | Which era contains ON? | A) MAP OF THE SOUL | B) BE | C) Proof | D) WINGS | ANSWER: A",
  "GE019 | Which era contains Life Goes On? | A) BE | B) Proof | C) LOVE YOURSELF | D) MAP OF THE SOUL | ANSWER: A",
  "GE020 | Which era contains Dynamite? | A) BE period | B) WINGS | C) School Trilogy | D) DARK & WILD | ANSWER: A",
  "GE021 | Which era contains Butter? | A) English-language singles period | B) School Trilogy | C) WINGS | D) LOVE YOURSELF | ANSWER: A",
  "GE022 | Which era contains Permission to Dance? | A) English-language singles period | B) DARK & WILD | C) WINGS | D) School Trilogy | ANSWER: A",
  "GE023 | Which era contains Yet To Come? | A) Proof | B) BE | C) LOVE YOURSELF | D) MAP OF THE SOUL | ANSWER: A",
  "GE024 | Which release is an anthology documenting BTS's history? | A) Proof | B) BE | C) WINGS | D) DARK & WILD | ANSWER: A",
  "GE025 | Which era is strongly associated with the theme of loving oneself? | A) LOVE YOURSELF | B) WINGS | C) School Trilogy | D) DARK & WILD | ANSWER: A",
  "GE026 | Which era is strongly associated with the concept of the psyche/self? | A) MAP OF THE SOUL | B) LOVE YOURSELF | C) WINGS | D) BE | ANSWER: A",
  "GE027 | Which era is associated with youth and its uncertainty? | A) The Most Beautiful Moment in Life | B) WINGS | C) Proof | D) BE | ANSWER: A",
  "GE028 | Which era came directly before LOVE YOURSELF? | A) You Never Walk Alone/WINGS period | B) MAP OF THE SOUL | C) BE | D) Proof | ANSWER: A",
  "GE029 | Which era followed LOVE YOURSELF? | A) MAP OF THE SOUL | B) WINGS | C) School Trilogy | D) DARK & WILD | ANSWER: A",
  "GE030 | Which era followed MAP OF THE SOUL? | A) BE | B) Proof | C) LOVE YOURSELF | D) WINGS | ANSWER: A",
  "GE031 | Which era followed BE as a major BTS album chapter? | A) Proof | B) WINGS | C) School Trilogy | D) DARK & WILD | ANSWER: A",
  "GE032 | Which era is connected with the album WINGS? | A) WINGS | B) LOVE YOURSELF | C) BE | D) Proof | ANSWER: A",
  "GE033 | Which era is connected with You Never Walk Alone? | A) WINGS continuation | B) LOVE YOURSELF | C) BE | D) MAP OF THE SOUL | ANSWER: A",
  "GE034 | Which era is connected with The Most Beautiful Moment in Life Pt.1? | A) HYYH | B) WINGS | C) LOVE YOURSELF | D) BE | ANSWER: A",
  "GE035 | Which era is connected with The Most Beautiful Moment in Life Pt.2? | A) HYYH | B) MAP OF THE SOUL | C) BE | D) Proof | ANSWER: A",
  "GE036 | Which era is connected with Young Forever? | A) HYYH | B) WINGS | C) LOVE YOURSELF | D) BE | ANSWER: A",
  "GE037 | Which era is associated with Danger? | A) DARK & WILD | B) WINGS | C) LOVE YOURSELF | D) HYYH | ANSWER: A",
  "GE038 | Which era is associated with War of Hormone? | A) DARK & WILD | B) School Trilogy | C) WINGS | D) BE | ANSWER: A",
  "GE039 | Which era is associated with Dope? | A) HYYH | B) WINGS | C) LOVE YOURSELF | D) MAP OF THE SOUL | ANSWER: A",
  "GE040 | Which era is associated with Butterfly? | A) HYYH | B) WINGS | C) BE | D) Proof | ANSWER: A",
  "GE041 | Which era is associated with House of Cards? | A) HYYH/Young Forever period | B) WINGS | C) MAP OF THE SOUL | D) BE | ANSWER: A",
  "GE042 | Which era is associated with Fire? | A) HYYH: Young Forever | B) LOVE YOURSELF | C) WINGS | D) Proof | ANSWER: A",
  "GE043 | Which era is associated with Save ME? | A) HYYH: Young Forever | B) MAP OF THE SOUL | C) BE | D) Proof | ANSWER: A",
  "GE044 | Which era is associated with Blood Sweat & Tears? | A) WINGS | B) HYYH | C) LOVE YOURSELF | D) BE | ANSWER: A",
  "GE045 | Which era is associated with Awake? | A) WINGS | B) LOVE YOURSELF | C) MAP OF THE SOUL | D) BE | ANSWER: A",
  "GE046 | Which era is associated with Begin? | A) WINGS | B) HYYH | C) Proof | D) BE | ANSWER: A",
  "GE047 | Which era is associated with Lie? | A) WINGS | B) LOVE YOURSELF | C) School Trilogy | D) MAP OF THE SOUL | ANSWER: A",
  "GE048 | Which era is associated with Stigma? | A) WINGS | B) BE | C) Proof | D) HYYH | ANSWER: A",
  "GE049 | Which era is associated with Reflection? | A) WINGS | B) LOVE YOURSELF | C) MAP OF THE SOUL | D) BE | ANSWER: A",
  "GE050 | Which era is associated with MAMA? | A) WINGS | B) HYYH | C) Proof | D) DARK & WILD | ANSWER: A",
  "GE051 | Which era is associated with First Love? | A) WINGS | B) School Trilogy | C) LOVE YOURSELF | D) BE | ANSWER: A",
  "GE052 | Which era is associated with DNA? | A) LOVE YOURSELF | B) HYYH | C) WINGS | D) MAP OF THE SOUL | ANSWER: A",
  "GE053 | Which era is associated with Serendipity? | A) LOVE YOURSELF | B) WINGS | C) BE | D) Proof | ANSWER: A",
  "GE054 | Which era is associated with Singularity? | A) LOVE YOURSELF | B) MAP OF THE SOUL | C) HYYH | D) BE | ANSWER: A",
  "GE055 | Which era is associated with Epiphany? | A) LOVE YOURSELF | B) WINGS | C) BE | D) School Trilogy | ANSWER: A",
  "GE056 | Which era is associated with Euphoria? | A) LOVE YOURSELF | B) HYYH | C) MAP OF THE SOUL | D) Proof | ANSWER: A",
  "GE057 | Which era is associated with Magic Shop? | A) LOVE YOURSELF | B) WINGS | C) BE | D) School Trilogy | ANSWER: A",
  "GE058 | Which era is associated with Pied Piper? | A) LOVE YOURSELF | B) MAP OF THE SOUL | C) BE | D) DARK & WILD | ANSWER: A",
  "GE059 | Which era is associated with IDOL? | A) LOVE YOURSELF | B) WINGS | C) HYYH | D) BE | ANSWER: A",
  "GE060 | Which era is associated with Fake Love? | A) LOVE YOURSELF | B) MAP OF THE SOUL | C) Proof | D) BE | ANSWER: A",
  "GE061 | Which era is associated with Answer: Love Myself? | A) LOVE YOURSELF | B) WINGS | C) HYYH | D) School Trilogy | ANSWER: A",
  "GE062 | Which era is associated with Persona? | A) MAP OF THE SOUL | B) LOVE YOURSELF | C) WINGS | D) BE | ANSWER: A",
  "GE063 | Which era is associated with Dionysus? | A) MAP OF THE SOUL | B) LOVE YOURSELF | C) HYYH | D) Proof | ANSWER: A",
  "GE064 | Which era is associated with Interlude: Shadow? | A) MAP OF THE SOUL | B) WINGS | C) BE | D) Proof | ANSWER: A",
  "GE065 | Which era is associated with Outro: Ego? | A) MAP OF THE SOUL | B) LOVE YOURSELF | C) HYYH | D) BE | ANSWER: A",
  "GE066 | Which era is associated with Filter? | A) MAP OF THE SOUL : 7 | B) LOVE YOURSELF | C) WINGS | D) BE | ANSWER: A",
  "GE067 | Which era is associated with Black Swan? | A) MAP OF THE SOUL : 7 | B) WINGS | C) LOVE YOURSELF | D) Proof | ANSWER: A",
  "GE068 | Which era is associated with Louder than Bombs? | A) MAP OF THE SOUL : 7 | B) BE | C) Proof | D) HYYH | ANSWER: A",
  "GE069 | Which era is associated with ON? | A) MAP OF THE SOUL : 7 | B) LOVE YOURSELF | C) WINGS | D) BE | ANSWER: A",
  "GE070 | Which era is associated with My Time? | A) MAP OF THE SOUL : 7 | B) LOVE YOURSELF | C) HYYH | D) Proof | ANSWER: A",
  "GE071 | Which era is associated with Inner Child? | A) MAP OF THE SOUL : 7 | B) WINGS | C) BE | D) HYYH | ANSWER: A",
  "GE072 | Which era is associated with Moon? | A) MAP OF THE SOUL : 7 | B) LOVE YOURSELF | C) Proof | D) BE | ANSWER: A",
  "GE073 | Which era is associated with Life Goes On? | A) BE | B) MAP OF THE SOUL | C) Proof | D) LOVE YOURSELF | ANSWER: A",
  "GE074 | Which era is associated with Fly to My Room? | A) BE | B) WINGS | C) LOVE YOURSELF | D) HYYH | ANSWER: A",
  "GE075 | Which era is associated with Blue & Grey? | A) BE | B) Proof | C) MAP OF THE SOUL | D) WINGS | ANSWER: A",
  "GE076 | Which era is associated with Telepathy? | A) BE | B) LOVE YOURSELF | C) HYYH | D) Proof | ANSWER: A",
  "GE077 | Which era is associated with Dis-ease? | A) BE | B) WINGS | C) MAP OF THE SOUL | D) School Trilogy | ANSWER: A",
  "GE078 | Which era is associated with Stay? | A) BE | B) Proof | C) LOVE YOURSELF | D) HYYH | ANSWER: A",
  "GE079 | Which era is associated with Dynamite? | A) BE-era period | B) WINGS | C) HYYH | D) School Trilogy | ANSWER: A",
  "GE080 | Which era is associated with Butter? | A) English-language singles period | B) HYYH | C) WINGS | D) LOVE YOURSELF | ANSWER: A",
  "GE081 | Which era is associated with Permission to Dance? | A) English-language singles period | B) MAP OF THE SOUL | C) BE | D) School Trilogy | ANSWER: A",
  "GE082 | Which era is associated with Yet To Come? | A) Proof | B) BE | C) LOVE YOURSELF | D) WINGS | ANSWER: A",
  "GE083 | Which era is associated with Run BTS? | A) Proof | B) HYYH | C) WINGS | D) BE | ANSWER: A",
  "GE084 | Which era is associated with For Youth? | A) Proof | B) LOVE YOURSELF | C) BE | D) MAP OF THE SOUL | ANSWER: A",
  "GE085 | Which era is associated with Take Two? | A) Proof-era period | B) WINGS | C) HYYH | D) School Trilogy | ANSWER: A",
  "GE086 | Which era is earliest among these? | A) School Trilogy | B) LOVE YOURSELF | C) MAP OF THE SOUL | D) BE | ANSWER: A",
  "GE087 | Which era came after DARK & WILD? | A) The Most Beautiful Moment in Life | B) WINGS | C) LOVE YOURSELF | D) MAP OF THE SOUL | ANSWER: A",
  "GE088 | Which era came after HYYH? | A) WINGS | B) BE | C) Proof | D) LOVE YOURSELF | ANSWER: A",
  "GE089 | Which era came after WINGS? | A) LOVE YOURSELF | B) HYYH | C) BE | D) School Trilogy | ANSWER: A",
  "GE090 | Which era came after LOVE YOURSELF? | A) MAP OF THE SOUL | B) WINGS | C) HYYH | D) BE | ANSWER: A",
  "GE091 | Which era came after MAP OF THE SOUL? | A) BE | B) Proof | C) WINGS | D) LOVE YOURSELF | ANSWER: A",
  "GE092 | Which major release came after BE? | A) Proof | B) WINGS | C) DARK & WILD | D) HYYH | ANSWER: A",
  "GE093 | Which era is most associated with school and teenage concerns? | A) School Trilogy | B) LOVE YOURSELF | C) MAP OF THE SOUL | D) BE | ANSWER: A",
  "GE094 | Which era is most strongly associated with youth, uncertainty and growing up? | A) HYYH | B) WINGS | C) Proof | D) BE | ANSWER: A",
  "GE095 | Which era is strongly associated with self-love? | A) LOVE YOURSELF | B) School Trilogy | C) DARK & WILD | D) WINGS | ANSWER: A",
  "GE096 | Which era explores persona, shadow and the inner self? | A) MAP OF THE SOUL | B) LOVE YOURSELF | C) HYYH | D) BE | ANSWER: A",
  "GE097 | Which album is an anthology of BTS's history? | A) Proof | B) BE | C) WINGS | D) Young Forever | ANSWER: A",
  "GE098 | Which release was created during the pandemic period and includes Life Goes On? | A) BE | B) Proof | C) MAP OF THE SOUL : 7 | D) LOVE YOURSELF 結 'Answer' | ANSWER: A",
  "GE099 | Which era includes the trilogy 承 'Her', 轉 'Tear' and 結 'Answer'? | A) LOVE YOURSELF | B) MAP OF THE SOUL | C) HYYH | D) WINGS | ANSWER: A",
  "GE100 | Which BTS chapter contains Persona and 7? | A) MAP OF THE SOUL | B) LOVE YOURSELF | C) WINGS | D) BE | ANSWER: A"
];

function parseLine(line, gameType) {
  const parts = line.split(' | ');
  const id = parts[0].trim();
  let question = '';
  let emojis = undefined;

  if (gameType === 'emoji') {
    emojis = parts[1].trim();
    question = parts[2].trim();
  } else {
    question = parts[1].trim();
  }

  const optA = (gameType === 'emoji' ? parts[3] : parts[2]).replace('A) ', '').trim();
  const optB = (gameType === 'emoji' ? parts[4] : parts[3]).replace('B) ', '').trim();
  const optC = (gameType === 'emoji' ? parts[5] : parts[4]).replace('C) ', '').trim();
  const optD = (gameType === 'emoji' ? parts[6] : parts[5]).replace('D) ', '').trim();

  const answerKey = (gameType === 'emoji' ? parts[7] : parts[6]).replace('ANSWER: ', '').trim();

  const optionsMap = { 'A': optA, 'B': optB, 'C': optC, 'D': optD };
  const correctAnswer = optionsMap[answerKey] || optA;

  const res = {
    id,
    gameType,
    question,
    options: [optA, optB, optC, optD],
    correctAnswer,
    explanation: `${correctAnswer} is the verified answer for "${question}".`,
    difficulty: "medium"
  };

  if (emojis) res.emojis = emojis;

  return res;
}

function processMasterQuestions() {
  console.log("Parsing EXACT 400 Master Questions from User Prompt...");
  const gsList = rawGS.map(l => parseLine(l, 'guess-song'));
  const gmList = rawGM.map(l => parseLine(l, 'guess-member'));
  const emList = rawEM.map(l => parseLine(l, 'emoji'));
  const geList = rawGE.map(l => parseLine(l, 'guess-era'));

  const masterList = [...gsList, ...gmList, ...emList, ...geList];

  console.log(`Successfully parsed ${masterList.length} EXACT master questions.`);

  fs.writeFileSync(targetJsonPath, JSON.stringify(masterList, null, 2), 'utf8');
  console.log(`Saved btsQuestionBank.json`);

  const jsContent = `// BTS World 400 Exact Master Question Bank
export const MASTER_QUIZ_DATABASE = ${JSON.stringify(masterList, null, 2)};
`;
  fs.writeFileSync(targetJsPath, jsContent, 'utf8');
  console.log(`Saved btsQuestionBank.js`);
}

processMasterQuestions();
